---
- name: example playbook with when and command module
  hosts: all
  become: true
    tasks:
      - name: Install Apache web-server for debian family
        command: apt install apache2 -y
        when: ansible_os_family == "Debian"
      - name: Install Httpd for redhat Family
        command: Yum install httpd -y
        when: ansible_os_family == "RedHat"
...
